In [2]:
# Importando as bibliotecas necessárias e apelidando para facilitar o desenvolvimento.
import pandas as pd

In [3]:
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas (1).csv")

In [3]:
df

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0             1  Montagem          72.62          41.77           111      0
1             2  Usinagem          81.65          34.08           128      0
2             3  Usinagem          68.87          39.44           159      0
3             4  Usinagem          66.84          34.52            98      0
4             5  Usinagem          66.23          31.57            94      0
5             6  Usinagem          64.79          37.09            83      0
6             7  Usinagem          85.02          36.34           106      1
7             8  Inspeção          60.31          33.77           124      0
8             9  Montagem          75.84          29.65            92      0
9            10  Inspeção          68.38          28.93           145      1
10           11  Usinagem          76.31          35.48           149      0
11           12  Inspeção          74.79          33.37           134      0
12           13  Usinagem          76.31          36.51           154      0
13           14  Montagem          63.28          33.71           129      0
14           15  Montagem          64.98          33.24            83      0
15           16  Montagem          81.48          30.50           102      0
16           17  Montagem          79.62          39.68            85      1
17           18  Inspeção          69.80          27.20            91      0
18           19  Inspeção          77.16          47.45            99      0
19           20  Usinagem          73.30          39.77           119      1
20           21  Inspeção          79.77          38.04            91      0
21           22  Usinagem          71.76          35.16            80      0
22           23  Inspeção          74.16          31.93           149      0
23           24  Usinagem          74.69          32.34           123      1
24           25  Usinagem          74.03          32.71           145      1
25           26  Usinagem          75.96          38.70            93      0
26           27  Usinagem          60.80          37.18           159      0
27           28  Montagem          69.37          35.90           122      1
28           29  Montagem          70.28          35.04           103      0
29           30  Inspeção          73.53          32.84            82      0
30           31  Montagem          63.59          42.29           159      1
31           32  Inspeção          68.91          32.66           155      0
32           33  Inspeção          77.62          35.70           108      1
33           34  Inspeção          73.32          32.18           129      1
34           35  Usinagem          78.24          31.93           158      0
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [ ]:
# Exibe as 5 primeiras
df.head()

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [ ]:
# Exibe as 5 últimas
df.tail()

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [ ]:
# Exibir linhas e colunas
df.shape

(40, 6)

In [ ]:
# Exibe 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     str
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), str(1)
memory usage: 2.3 KB

In [ ]:
# Exibe as colunas
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [ ]:
# Realizaa contagem de valores
df.isna().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [10]:
df.isnull().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [ ]:
# Valores não nulos
df.notnull().sum()

    id_registro  setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0          True   True           True           True          True   True
1          True   True           True           True          True   True
2          True   True           True           True          True   True
3          True   True           True           True          True   True
4          True   True           True           True          True   True
5          True   True           True           True          True   True
6          True   True           True           True          True   True
7          True   True           True           True          True   True
8          True   True           True           True          True   True
9          True   True           True           True          True   True
10         True   True           True           True          True   True
11         True   True           True           True          True   True
12         True   True           True           True          True   True
13         True   True           True           True          True   True
14         True   True           True           True          True   True
15         True   True           True           True          True   True
16         True   True           True           True          True   True
17         True   True           True           True          True   True
18         True   True           True           True          True   True
19         True   True           True           True          True   True
20         True   True           True           True          True   True
21         True   True           True           True          True   True
22         True   True           True           True          True   True
23         True   True           True           True          True   True
24         True   True           True           True          True   True
25         True   True           True           True          True   True
26         True   True           True           True          True   True
27         True   True           True           True          True   True
28         True   True           True           True          True   True
29         True   True           True           True          True   True
30         True   True           True           True          True   True
31         True   True           True           True          True   True
32         True   True           True           True          True   True
33         True   True           True           True          True   True
34         True   True           True           True          True   True
35         True   True           True           True          True   True
36         True   True           True           True          True   True
37         True   True           True           True          True   True
38         True   True           True           True          True   True
39         True   True           True           True          True   True

In [ ]:
# Filtrar por colunas
df["temperatura_c"]

0     72.62
1     81.65
2     68.87
3     66.84
4     66.23
5     64.79
6     85.02
7     60.31
8     75.84
9     68.38
10    76.31
11    74.79
12    76.31
13    63.28
14    64.98
15    81.48
16    79.62
17    69.80
18    77.16
19    73.30
20    79.77
21    71.76
22    74.16
23    74.69
24    74.03
25    75.96
26    60.80
27    69.37
28    70.28
29    73.53
30    63.59
31    68.91
32    77.62
33    73.32
34    78.24
35    68.47
36    75.62
37    78.50
38    76.19
39    68.64
Name: temperatura_c, dtype: float64

In [13]:
df["id_registro"]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
32    33
33    34
34    35
35    36
36    37
37    38
38    39
39    40
Name: id_registro, dtype: int64

In [ ]:
# Comando para visualizar as colunas em forma de lista
df.columns.to_list()

['id_registro',
 'setor',
 'temperatura_c',
 'tempo_ciclo_s',
 'producao_dia',
 'falha']

In [15]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000

## Exercício

- 1.    Importem a biblioteca "pandas"
- 2.    Realizar a leitura dos dados
- 3.    Exibir os 5 primeiros dados
- 4.    Exibir os 5 últimos dados
- 5.    Exibir a quantidade de linhas e colunas
- 6.    Exibir as informações gerais dessa base de dados
- 7.    Realizar a contagem de valores não nulos
- 8.    Exibir os nomes das colunas
- 9.    Exibir a descrição (min, max, mean, std, quartis)

In [4]:
# 1. IMPORTANDO A BIBLIOTECA "PANDAS"
import pandas as pd

In [5]:
# 2. REALIZANDO A LEITURA DE DADOS
df = pd.read_csv(r".\data\dataset_aula01_techshop_vendas.csv")

In [ ]:
# 3. EXIBE OS 5 PRIMEIROS
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9

In [ ]:
# 4. EXIBE OS 5 ÚLTIMOS
df.tail()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
795,2024-12-27,Áudio,1128.44,4,Sul,Orgânico,4.6
796,2024-12-27,Acessórios,209.29,4,Sudeste,Google Ads,3.8
797,2024-12-28,Notebooks,7979.84,2,Sudeste,Google Ads,4.4
798,2024-12-28,Notebooks,4168.01,1,Nordeste,Instagram,4.1
799,2024-12-28,Acessórios,111.95,1,Sul,Google Ads,4.7

In [ ]:
# 5. EXIBE LINHAS, COLUNAS
df.shape

(800, 7)

In [ ]:
# 6. EXIBI AS INFORMAÇÕES GERAIS DA BASE DE DADOS
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    str
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
dtypes: float64(2), int64(1), str(4)
memory usage: 70.9 KB

In [24]:
# 7. CONTAGEM DE VALORES NÃO NULOS
df.notnull().sum()

data_pedido        800
categoria          800
preco_unitario     800
quantidade         800
regiao             800
canal_marketing    800
avaliacao          800
dtype: int64

In [ ]:
# 8. EXIBE OS NOMES DAS COLUNAS, (to.list - nativo do python)
df.columns.to_list()

['data_pedido',
 'categoria',
 'preco_unitario',
 'quantidade',
 'regiao',
 'canal_marketing',
 'avaliacao']

In [ ]:
# 9. EXIBE A DESCRIÇÃO (count, mean, std, min, quartis, max)
df.describe()

       preco_unitario  quantidade   avaliacao
count      800.000000  800.000000  800.000000
mean      2173.764038    2.237500    4.165500
std       2042.173946    1.306034    0.542658
min         20.070000    1.000000    2.400000
25%        249.837500    1.000000    3.800000
50%       1458.565000    2.000000    4.200000
75%       3707.427500    3.000000    4.600000
max       7979.840000    5.000000    5.000000

In [9]:
df["faturamento"] = df["preco_unitario"] * df["quantidade"]
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao,faturamento
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3,36.20
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4,613.05
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6,604.76
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1,6798.32
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9,6361.88

In [10]:
df = pd.read_csv(r"data\dataset_aula01_techshop_vendas.csv", parse_dates=[("data_pedido")])

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    datetime64[us]
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 63.1 KB

In [13]:
df["faturamento"] = df["preco_unitario"] * df["quantidade"]
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao,faturamento
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3,36.20
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4,613.05
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6,604.76
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1,6798.32
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9,6361.88

In [14]:
df["faturamento"]

0         36.20
1        613.05
2        604.76
3       6798.32
4       6361.88
         ...
795     4513.76
796      837.16
797    15959.68
798     4168.01
799      111.95
Name: faturamento, Length: 800, dtype: float64

In [ ]:
df_tratado = df.copy()